### ISSUE TITLE
Only Error messages

### ISSUE THREAD

**Issue by mischugo** [seafoodbuffet/gMapToGPX#1]
The bookmark doesn't work at all for me :-(

http://www.gmap-pedometer.com/?r=6196705

gMapToGPX v6.4.11 (ERROR)

There doesn't seem to be any extractable data on this page.

If there is, but it's not detected, please visit the project homepage and leave a bug report, including a link to the page you're on right now.

Note: Google Maps mashups (that is, a page with a Google Map on it, but not at google.com) do not automatically work with this utility.

**Comment by seafoodbuffet** [comment]
Hi there, I just tried your map and it _appears_ to work okay for me in safari and chrome. One quick question, are you waiting for the page to fully load prior to clicking the bookmarklet? What you're describing happens for me if I click the bookmarklet as soon as I try to load the page, but before the map fully renders.

**Comment by mischugo** [comment]
You are right, i have to wait for a more longer time!!!! Perfect

 Thanks a lot

By the way, i am looking for a site like gmap, but without ads and with the possibility to move the trackpoints as i like. But better would be, to have the aption to put a distance in a formfield, lets say 50 kilometer, then get a ring-tool (like photoshop) to lay down this 50Kilometer area an the map …
Sounds complicated, sorry about my english

Am 08.02.2014 um 00:05 schrieb Seafoodbuffet notifications@github.com:

**Comment by seafoodbuffet** [comment]
Hmm, I've never encountered something like that, sorry... But I'm glad that it's working for you now.
